package io.github.koogcompose.device.session

import androidx.room.*
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

/**
 * Shared Room database for Koog orchestration.
 * Defined in `commonMain` for CMP parity.
 */
@Database(
    entities = [SessionEntity::class, MessageEntity::class, ContextVarEntity::class],
    version = 1
)
@ConstructedBy(KoogDatabaseConstructor::class)
public abstract class KoogDatabase : RoomDatabase() {
    /** Returns the DAO for session management. */
    public abstract fun koogSessionDao(): KoogSessionDao
}

/**
 * Required for Room KMP to generate the database implementation.
 * The actual implementation is generated by the Room compiler.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
public expect object KoogDatabaseConstructor : RoomDatabaseConstructor<KoogDatabase>

/**
 * Shared factory to create the database instance across platforms.
 * 
 * @param builder The platform-specific builder (e.g., from `Room.databaseBuilder`).
 */
public fun createKoogDatabase(
    builder: RoomDatabase.Builder<KoogDatabase>
): KoogDatabase {
    return builder
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()
}
